/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/complete": {
    /** Get a forecast for a given location. */
    get: operations["complete"];
  };
}

export interface definitions {
  /** A weather forecast for a specific location. */
  forecast: {
    /** Geojson type. */
    type: "Feature";
    /** Geojson geometry. */
    geometry: {
      type: "Point";
      coordinates: number[];
    };
    properties: definitions["forecast_properties"];
  };
  /** Container for the forecast itself. */
  forecast_properties: {
    meta: definitions["forecast_meta"];
    /** Forecast time steps. */
    timeseries: definitions["forecast_timestep"][];
  };
  /** Metadata about the forecast. */
  forecast_meta: {
    /** Last update time for this location. */
    updated_at: string;
    /** Units used in forecast. */
    units: { [key: string]: string };
  };
  /** Forecast for a single timestep. */
  forecast_timestep: {
    /** Valid time. */
    time: string;
    data: definitions["forecast_details"];
  };
  /** Forecast details. */
  forecast_details: {
    instant?: definitions["forecast_data"];
    next_1_hours?: definitions["forecast_data"];
    next_6_hours?: definitions["forecast_data"];
    next_12_hours?: definitions["forecast_data"];
  };
  /** Forecast for a specific time range. */
  forecast_data: {
    summary?: definitions["forecast_summary"];
    /** Forecast values. */
    details?: { [key: string]: number };
  };
  /** Textual forecast data. */
  forecast_summary: {
    symbol_code?: definitions["weather_symbol"];
    symbol_confidence?: definitions["symbol_confidence"];
  };
  /** Certainty of a weather symbol. */
  symbol_confidence: "certain" | "somewhat certain" | "uncertain";
  /** An identifier that sums up the weather condition for this time period. May be used with https://api.met.no/weatherapi/weathericon/2.0/. */
  weather_symbol:
    | "clearsky_day"
    | "clearsky_night"
    | "clearsky_polartwilight"
    | "fair_day"
    | "fair_night"
    | "fair_polartwilight"
    | "lightssnowshowersandthunder_day"
    | "lightssnowshowersandthunder_night"
    | "lightssnowshowersandthunder_polartwilight"
    | "lightsnowshowers_day"
    | "lightsnowshowers_night"
    | "lightsnowshowers_polartwilight"
    | "heavyrainandthunder"
    | "heavysnowandthunder"
    | "rainandthunder"
    | "heavysleetshowersandthunder_day"
    | "heavysleetshowersandthunder_night"
    | "heavysleetshowersandthunder_polartwilight"
    | "heavysnow"
    | "heavyrainshowers_day"
    | "heavyrainshowers_night"
    | "heavyrainshowers_polartwilight"
    | "lightsleet"
    | "heavyrain"
    | "lightrainshowers_day"
    | "lightrainshowers_night"
    | "lightrainshowers_polartwilight"
    | "heavysleetshowers_day"
    | "heavysleetshowers_night"
    | "heavysleetshowers_polartwilight"
    | "lightsleetshowers_day"
    | "lightsleetshowers_night"
    | "lightsleetshowers_polartwilight"
    | "snow"
    | "heavyrainshowersandthunder_day"
    | "heavyrainshowersandthunder_night"
    | "heavyrainshowersandthunder_polartwilight"
    | "snowshowers_day"
    | "snowshowers_night"
    | "snowshowers_polartwilight"
    | "fog"
    | "snowshowersandthunder_day"
    | "snowshowersandthunder_night"
    | "snowshowersandthunder_polartwilight"
    | "lightsnowandthunder"
    | "heavysleetandthunder"
    | "lightrain"
    | "rainshowersandthunder_day"
    | "rainshowersandthunder_night"
    | "rainshowersandthunder_polartwilight"
    | "rain"
    | "lightsnow"
    | "lightrainshowersandthunder_day"
    | "lightrainshowersandthunder_night"
    | "lightrainshowersandthunder_polartwilight"
    | "heavysleet"
    | "sleetandthunder"
    | "lightrainandthunder"
    | "sleet"
    | "lightssleetshowersandthunder_day"
    | "lightssleetshowersandthunder_night"
    | "lightssleetshowersandthunder_polartwilight"
    | "lightsleetandthunder"
    | "partlycloudy_day"
    | "partlycloudy_night"
    | "partlycloudy_polartwilight"
    | "sleetshowersandthunder_day"
    | "sleetshowersandthunder_night"
    | "sleetshowersandthunder_polartwilight"
    | "rainshowers_day"
    | "rainshowers_night"
    | "rainshowers_polartwilight"
    | "snowandthunder"
    | "sleetshowers_day"
    | "sleetshowers_night"
    | "sleetshowers_polartwilight"
    | "cloudy"
    | "heavysnowshowersandthunder_day"
    | "heavysnowshowersandthunder_night"
    | "heavysnowshowersandthunder_polartwilight"
    | "heavysnowshowers_day"
    | "heavysnowshowers_night"
    | "heavysnowshowers_polartwilight";
}

export interface operations {
  /** Get a forecast for a given location. */
  complete: {
    parameters: {
      query: {
        /** Latitude to get forecast for. */
        lat: number;
        /** Longitude to get forecast for. */
        lon: number;
        /** Provide your own topography elevation above sea level. May give a better forecast. */
        altitude?: number;
      };
    };
    responses: {
      /** A weather forecast for a given location. */
      200: {
        schema: definitions["forecast"];
      };
    };
  };
}
